name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main   # Cambia si tu rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:opening-entrenubes --token ${{ secrets.FIREBASE_TOKEN }}

